os:
  - linux
sudo: false
git:
  depth: false
  submodules: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
      - lib32stdc++6
before_script:
  - git clone -b dev https://github.com/flutter/flutter.git ~/flutter
  - FLUTTER_PATH=~/flutter/bin
  - PUB_CACHE_BIN=~/.pub-cache/bin
  - DART_PATH=~/flutter/bin/cache/dart-sdk/bin
  - export PATH=$PATH:$FLUTTER_PATH:$PUB_CACHE_BIN:$DART_PATH
  - flutter doctor
  - pub global activate webdev
  - pub global activate -sgit https://github.com/boyan01/peanut.dart.git
script:
  - flutter pub upgrade
  - dart tools/bqb_json_gen.dart
  - peanut
deploy:
  local_dir: .peanutOutput/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
